source 'http://rubygems.org'

gem 'rails', '3.1.3'
gem 'bcrypt-ruby'



# Bundle edge Rails instead:
# gem 'rails',     :git => 'git://github.com/rails/rails.git'

#gem 'sqlite3'
gem 'pg'
gem 'eventmachine', "~>1.0.0.beta" 
gem 'em-websocket'
gem 'algorithms'
gem 'em-priority-queue', "~> 1.0.0"
gem 'em-http-request'
gem 'simple_oauth'
gem 'yajl-ruby'


#
# ACA Core Plugins
#
gem 'login', :path => 'vendor/acacore/login'
gem 'podsystem', :path => '../../interfaces/podsystem'


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails', "  ~> 3.1.4"
  gem 'coffee-rails', "~> 3.1.1"
  gem 'uglifier', "1.0.3"
end

gem 'jquery-rails'
gem 'rails_admin', :path => '../../admin'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'

group :test do
  # Pretty printed test output
  gem 'turn', :require => false
end
