source 'http://rubygems.org'

#
# Rails related
#
gem 'rails'
gem 'jquery-rails'
gem 'bcrypt-ruby'


#
# Admin interface
#
gem 'rails_admin', :git => 'git://github.com/sferik/rails_admin.git'


#
# Database
#
gem 'pg'

#
# Required for control
#
gem 'eventmachine', ">= 1.0.0.beta.3"	# Evented comms
gem 'em-websocket'						# Web page communication
gem 'em-priority-queue'					# Command Queueing
gem 'em-http-request'					# HTTP service support
#gem 'em-resolv-replace'					# Evented DNS resolver (double resume with net/ldap)
gem 'atomic'							# Atomic operations


#
# ACA Core Plugins
#
gem 'login', :git => 'git://github.com/stakach/advanced-authenticator.git'


#
# Per-Project requirements
#
gem 'simple_oauth'			# for Twitter auth
gem 'yajl-ruby'				# Required for JSONResponse middleware in em-http-request

gem 'padsystem', :path => '../../interfaces/padsystem'
gem 'flexible_interface', :path => '../../interfaces/example'



# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails', ">= 3.1.4"
  gem 'coffee-rails', ">= 3.1.1"
  gem 'uglifier', ">= 1.0.3"
end

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'

group :test do
  # Pretty printed test output
  gem 'turn', :require => false
end
